// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { demos as dm0, frontmatter as fm0, toc as toc0, texts as txt0 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/docs/components/icon/index.en.md?type=meta';
import { demos as dm1, frontmatter as fm1, toc as toc1, texts as txt1 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/docs/components/icon/index.zh.md?type=meta';
import { demos as dm2, frontmatter as fm2, toc as toc2, texts as txt2 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/docs/guide/quick-start.en.md?type=meta';
import { demos as dm3, frontmatter as fm3, toc as toc3, texts as txt3 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/docs/guide/quick-start.zh.md?type=meta';
import { demos as dm4, frontmatter as fm4, toc as toc4, texts as txt4 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/docs/guide/theming.en.md?type=meta';
import { demos as dm5, frontmatter as fm5, toc as toc5, texts as txt5 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/docs/guide/theming.zh.md?type=meta';
import { demos as dm6, frontmatter as fm6, toc as toc6, texts as txt6 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/docs/guide/i18n.en.md?type=meta';
import { demos as dm7, frontmatter as fm7, toc as toc7, texts as txt7 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/docs/guide/i18n.zh.md?type=meta';
import { demos as dm8, frontmatter as fm8, toc as toc8, texts as txt8 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/docs/index.en.md?type=meta';
import { demos as dm9, frontmatter as fm9, toc as toc9, texts as txt9 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/docs/index.zh.md?type=meta';
import { demos as dm10, frontmatter as fm10, toc as toc10, texts as txt10 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/auto-center/index.en.md?type=meta';
import { demos as dm11, frontmatter as fm11, toc as toc11, texts as txt11 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/auto-center/index.zh.md?type=meta';
import { demos as dm12, frontmatter as fm12, toc as toc12, texts as txt12 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/avatar/index.en.md?type=meta';
import { demos as dm13, frontmatter as fm13, toc as toc13, texts as txt13 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/avatar/index.zh.md?type=meta';
import { demos as dm14, frontmatter as fm14, toc as toc14, texts as txt14 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/badge/index.en.md?type=meta';
import { demos as dm15, frontmatter as fm15, toc as toc15, texts as txt15 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/badge/index.zh.md?type=meta';
import { demos as dm16, frontmatter as fm16, toc as toc16, texts as txt16 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/button/index.en.md?type=meta';
import { demos as dm17, frontmatter as fm17, toc as toc17, texts as txt17 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/button/index.zh.md?type=meta';
import { demos as dm18, frontmatter as fm18, toc as toc18, texts as txt18 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/calendar/index.en.md?type=meta';
import { demos as dm19, frontmatter as fm19, toc as toc19, texts as txt19 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/calendar/index.zh.md?type=meta';
import { demos as dm20, frontmatter as fm20, toc as toc20, texts as txt20 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/capsule-tabs/index.en.md?type=meta';
import { demos as dm21, frontmatter as fm21, toc as toc21, texts as txt21 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/capsule-tabs/index.zh.md?type=meta';
import { demos as dm22, frontmatter as fm22, toc as toc22, texts as txt22 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/card/index.en.md?type=meta';
import { demos as dm23, frontmatter as fm23, toc as toc23, texts as txt23 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/card/index.zh.md?type=meta';
import { demos as dm24, frontmatter as fm24, toc as toc24, texts as txt24 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/collapse/index.en.md?type=meta';
import { demos as dm25, frontmatter as fm25, toc as toc25, texts as txt25 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/collapse/index.zh.md?type=meta';
import { demos as dm26, frontmatter as fm26, toc as toc26, texts as txt26 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/config-provider/index.en.md?type=meta';
import { demos as dm27, frontmatter as fm27, toc as toc27, texts as txt27 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/config-provider/index.zh.md?type=meta';
import { demos as dm28, frontmatter as fm28, toc as toc28, texts as txt28 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/divider/index.en.md?type=meta';
import { demos as dm29, frontmatter as fm29, toc as toc29, texts as txt29 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/divider/index.zh.md?type=meta';
import { demos as dm30, frontmatter as fm30, toc as toc30, texts as txt30 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/ellipsis/index.en.md?type=meta';
import { demos as dm31, frontmatter as fm31, toc as toc31, texts as txt31 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/ellipsis/index.zh.md?type=meta';
import { demos as dm32, frontmatter as fm32, toc as toc32, texts as txt32 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/error-block/index.en.md?type=meta';
import { demos as dm33, frontmatter as fm33, toc as toc33, texts as txt33 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/error-block/index.zh.md?type=meta';
import { demos as dm34, frontmatter as fm34, toc as toc34, texts as txt34 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/floating-panel/index.en.md?type=meta';
import { demos as dm35, frontmatter as fm35, toc as toc35, texts as txt35 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/floating-panel/index.zh.md?type=meta';
import { demos as dm36, frontmatter as fm36, toc as toc36, texts as txt36 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/footer/index.en.md?type=meta';
import { demos as dm37, frontmatter as fm37, toc as toc37, texts as txt37 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/footer/index.zh.md?type=meta';
import { demos as dm38, frontmatter as fm38, toc as toc38, texts as txt38 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/form/index.en.md?type=meta';
import { demos as dm39, frontmatter as fm39, toc as toc39, texts as txt39 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/form/index.zh.md?type=meta';
import { demos as dm40, frontmatter as fm40, toc as toc40, texts as txt40 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/grid/index.en.md?type=meta';
import { demos as dm41, frontmatter as fm41, toc as toc41, texts as txt41 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/grid/index.zh.md?type=meta';
import { demos as dm42, frontmatter as fm42, toc as toc42, texts as txt42 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/image-viewer/index.en.md?type=meta';
import { demos as dm43, frontmatter as fm43, toc as toc43, texts as txt43 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/image-viewer/index.zh.md?type=meta';
import { demos as dm44, frontmatter as fm44, toc as toc44, texts as txt44 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/image/index.en.md?type=meta';
import { demos as dm45, frontmatter as fm45, toc as toc45, texts as txt45 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/image/index.zh.md?type=meta';
import { demos as dm46, frontmatter as fm46, toc as toc46, texts as txt46 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/index-bar/index.zh.md?type=meta';
import { demos as dm47, frontmatter as fm47, toc as toc47, texts as txt47 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/infinite-scroll/index.en.md?type=meta';
import { demos as dm48, frontmatter as fm48, toc as toc48, texts as txt48 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/infinite-scroll/index.zh.md?type=meta';
import { demos as dm49, frontmatter as fm49, toc as toc49, texts as txt49 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/input/index.en.md?type=meta';
import { demos as dm50, frontmatter as fm50, toc as toc50, texts as txt50 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/input/index.zh.md?type=meta';
import { demos as dm51, frontmatter as fm51, toc as toc51, texts as txt51 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/jumbo-tabs/index.en.md?type=meta';
import { demos as dm52, frontmatter as fm52, toc as toc52, texts as txt52 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/jumbo-tabs/index.zh.md?type=meta';
import { demos as dm53, frontmatter as fm53, toc as toc53, texts as txt53 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/list/index.en.md?type=meta';
import { demos as dm54, frontmatter as fm54, toc as toc54, texts as txt54 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/list/index.zh.md?type=meta';
import { demos as dm55, frontmatter as fm55, toc as toc55, texts as txt55 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/loading/index.en.md?type=meta';
import { demos as dm56, frontmatter as fm56, toc as toc56, texts as txt56 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/loading/index.zh.md?type=meta';
import { demos as dm57, frontmatter as fm57, toc as toc57, texts as txt57 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/mask/index.en.md?type=meta';
import { demos as dm58, frontmatter as fm58, toc as toc58, texts as txt58 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/mask/index.zh.md?type=meta';
import { demos as dm59, frontmatter as fm59, toc as toc59, texts as txt59 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/nav-bar/index.en.md?type=meta';
import { demos as dm60, frontmatter as fm60, toc as toc60, texts as txt60 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/nav-bar/index.zh.md?type=meta';
import { demos as dm61, frontmatter as fm61, toc as toc61, texts as txt61 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/page-indicator/index.en.md?type=meta';
import { demos as dm62, frontmatter as fm62, toc as toc62, texts as txt62 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/page-indicator/index.zh.md?type=meta';
import { demos as dm63, frontmatter as fm63, toc as toc63, texts as txt63 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/popover/index.en.md?type=meta';
import { demos as dm64, frontmatter as fm64, toc as toc64, texts as txt64 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/popover/index.zh.md?type=meta';
import { demos as dm65, frontmatter as fm65, toc as toc65, texts as txt65 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/safe-area/index.en.md?type=meta';
import { demos as dm66, frontmatter as fm66, toc as toc66, texts as txt66 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/safe-area/index.zh.md?type=meta';
import { demos as dm67, frontmatter as fm67, toc as toc67, texts as txt67 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/scroll-mask/index.en.md?type=meta';
import { demos as dm68, frontmatter as fm68, toc as toc68, texts as txt68 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/scroll-mask/index.zh.md?type=meta';
import { demos as dm69, frontmatter as fm69, toc as toc69, texts as txt69 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/selector/index.en.md?type=meta';
import { demos as dm70, frontmatter as fm70, toc as toc70, texts as txt70 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/selector/index.zh.md?type=meta';
import { demos as dm71, frontmatter as fm71, toc as toc71, texts as txt71 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/side-bar/index.en.md?type=meta';
import { demos as dm72, frontmatter as fm72, toc as toc72, texts as txt72 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/side-bar/index.zh.md?type=meta';
import { demos as dm73, frontmatter as fm73, toc as toc73, texts as txt73 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/space/index.en.md?type=meta';
import { demos as dm74, frontmatter as fm74, toc as toc74, texts as txt74 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/space/index.zh.md?type=meta';
import { demos as dm75, frontmatter as fm75, toc as toc75, texts as txt75 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/stepper/index.en.md?type=meta';
import { demos as dm76, frontmatter as fm76, toc as toc76, texts as txt76 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/stepper/index.zh.md?type=meta';
import { demos as dm77, frontmatter as fm77, toc as toc77, texts as txt77 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/steps/index.en.md?type=meta';
import { demos as dm78, frontmatter as fm78, toc as toc78, texts as txt78 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/steps/index.zh.md?type=meta';
import { demos as dm79, frontmatter as fm79, toc as toc79, texts as txt79 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/swiper/index.en.md?type=meta';
import { demos as dm80, frontmatter as fm80, toc as toc80, texts as txt80 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/swiper/index.zh.md?type=meta';
import { demos as dm81, frontmatter as fm81, toc as toc81, texts as txt81 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/switch/index.en.md?type=meta';
import { demos as dm82, frontmatter as fm82, toc as toc82, texts as txt82 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/switch/index.zh.md?type=meta';
import { demos as dm83, frontmatter as fm83, toc as toc83, texts as txt83 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/tab-bar/index.en.md?type=meta';
import { demos as dm84, frontmatter as fm84, toc as toc84, texts as txt84 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/tab-bar/index.zh.md?type=meta';
import { demos as dm85, frontmatter as fm85, toc as toc85, texts as txt85 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/tabs/index.en.md?type=meta';
import { demos as dm86, frontmatter as fm86, toc as toc86, texts as txt86 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/tabs/index.zh.md?type=meta';
import { demos as dm87, frontmatter as fm87, toc as toc87, texts as txt87 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/tag/index.en.md?type=meta';
import { demos as dm88, frontmatter as fm88, toc as toc88, texts as txt88 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/tag/index.zh.md?type=meta';
import { demos as dm89, frontmatter as fm89, toc as toc89, texts as txt89 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/text-area/index.en.md?type=meta';
import { demos as dm90, frontmatter as fm90, toc as toc90, texts as txt90 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/text-area/index.zh.md?type=meta';
import { demos as dm91, frontmatter as fm91, toc as toc91, texts as txt91 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/toast/index.en.md?type=meta';
import { demos as dm92, frontmatter as fm92, toc as toc92, texts as txt92 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/toast/index.zh.md?type=meta';
import { demos as dm93, frontmatter as fm93, toc as toc93, texts as txt93 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/water-mark/index.en.md?type=meta';
import { demos as dm94, frontmatter as fm94, toc as toc94, texts as txt94 } from 'C:/Users/mel/Desktop/project/black-ui-mobile/src/water-mark/index.zh.md?type=meta';

export { components } from './atoms';
export { tabs } from './tabs';

export const filesMeta = {
  'docs/components/icon/index.en': {
    frontmatter: fm0,
    toc: toc0,
    texts: txt0,
    demos: dm0,
  },
  'docs/components/icon/index.zh': {
    frontmatter: fm1,
    toc: toc1,
    texts: txt1,
    demos: dm1,
  },
  'docs/guide/quick-start.en': {
    frontmatter: fm2,
    toc: toc2,
    texts: txt2,
    demos: dm2,
  },
  'docs/guide/quick-start.zh': {
    frontmatter: fm3,
    toc: toc3,
    texts: txt3,
    demos: dm3,
  },
  'docs/guide/theming.en': {
    frontmatter: fm4,
    toc: toc4,
    texts: txt4,
    demos: dm4,
  },
  'docs/guide/theming.zh': {
    frontmatter: fm5,
    toc: toc5,
    texts: txt5,
    demos: dm5,
  },
  'docs/guide/i18n.en': {
    frontmatter: fm6,
    toc: toc6,
    texts: txt6,
    demos: dm6,
  },
  'docs/guide/i18n.zh': {
    frontmatter: fm7,
    toc: toc7,
    texts: txt7,
    demos: dm7,
  },
  'docs/index.en': {
    frontmatter: fm8,
    toc: toc8,
    texts: txt8,
    demos: dm8,
  },
  'docs/index.zh': {
    frontmatter: fm9,
    toc: toc9,
    texts: txt9,
    demos: dm9,
  },
  'components/auto-center/index.en': {
    frontmatter: fm10,
    toc: toc10,
    texts: txt10,
    demos: dm10,
  },
  'components/auto-center/index.zh': {
    frontmatter: fm11,
    toc: toc11,
    texts: txt11,
    demos: dm11,
  },
  'components/avatar/index.en': {
    frontmatter: fm12,
    toc: toc12,
    texts: txt12,
    demos: dm12,
  },
  'components/avatar/index.zh': {
    frontmatter: fm13,
    toc: toc13,
    texts: txt13,
    demos: dm13,
  },
  'components/badge/index.en': {
    frontmatter: fm14,
    toc: toc14,
    texts: txt14,
    demos: dm14,
  },
  'components/badge/index.zh': {
    frontmatter: fm15,
    toc: toc15,
    texts: txt15,
    demos: dm15,
  },
  'components/button/index.en': {
    frontmatter: fm16,
    toc: toc16,
    texts: txt16,
    demos: dm16,
  },
  'components/button/index.zh': {
    frontmatter: fm17,
    toc: toc17,
    texts: txt17,
    demos: dm17,
  },
  'components/calendar/index.en': {
    frontmatter: fm18,
    toc: toc18,
    texts: txt18,
    demos: dm18,
  },
  'components/calendar/index.zh': {
    frontmatter: fm19,
    toc: toc19,
    texts: txt19,
    demos: dm19,
  },
  'components/capsule-tabs/index.en': {
    frontmatter: fm20,
    toc: toc20,
    texts: txt20,
    demos: dm20,
  },
  'components/capsule-tabs/index.zh': {
    frontmatter: fm21,
    toc: toc21,
    texts: txt21,
    demos: dm21,
  },
  'components/card/index.en': {
    frontmatter: fm22,
    toc: toc22,
    texts: txt22,
    demos: dm22,
  },
  'components/card/index.zh': {
    frontmatter: fm23,
    toc: toc23,
    texts: txt23,
    demos: dm23,
  },
  'components/collapse/index.en': {
    frontmatter: fm24,
    toc: toc24,
    texts: txt24,
    demos: dm24,
  },
  'components/collapse/index.zh': {
    frontmatter: fm25,
    toc: toc25,
    texts: txt25,
    demos: dm25,
  },
  'components/config-provider/index.en': {
    frontmatter: fm26,
    toc: toc26,
    texts: txt26,
    demos: dm26,
  },
  'components/config-provider/index.zh': {
    frontmatter: fm27,
    toc: toc27,
    texts: txt27,
    demos: dm27,
  },
  'components/divider/index.en': {
    frontmatter: fm28,
    toc: toc28,
    texts: txt28,
    demos: dm28,
  },
  'components/divider/index.zh': {
    frontmatter: fm29,
    toc: toc29,
    texts: txt29,
    demos: dm29,
  },
  'components/ellipsis/index.en': {
    frontmatter: fm30,
    toc: toc30,
    texts: txt30,
    demos: dm30,
  },
  'components/ellipsis/index.zh': {
    frontmatter: fm31,
    toc: toc31,
    texts: txt31,
    demos: dm31,
  },
  'components/error-block/index.en': {
    frontmatter: fm32,
    toc: toc32,
    texts: txt32,
    demos: dm32,
  },
  'components/error-block/index.zh': {
    frontmatter: fm33,
    toc: toc33,
    texts: txt33,
    demos: dm33,
  },
  'components/floating-panel/index.en': {
    frontmatter: fm34,
    toc: toc34,
    texts: txt34,
    demos: dm34,
  },
  'components/floating-panel/index.zh': {
    frontmatter: fm35,
    toc: toc35,
    texts: txt35,
    demos: dm35,
  },
  'components/footer/index.en': {
    frontmatter: fm36,
    toc: toc36,
    texts: txt36,
    demos: dm36,
  },
  'components/footer/index.zh': {
    frontmatter: fm37,
    toc: toc37,
    texts: txt37,
    demos: dm37,
  },
  'components/form/index.en': {
    frontmatter: fm38,
    toc: toc38,
    texts: txt38,
    demos: dm38,
  },
  'components/form/index.zh': {
    frontmatter: fm39,
    toc: toc39,
    texts: txt39,
    demos: dm39,
  },
  'components/grid/index.en': {
    frontmatter: fm40,
    toc: toc40,
    texts: txt40,
    demos: dm40,
  },
  'components/grid/index.zh': {
    frontmatter: fm41,
    toc: toc41,
    texts: txt41,
    demos: dm41,
  },
  'components/image-viewer/index.en': {
    frontmatter: fm42,
    toc: toc42,
    texts: txt42,
    demos: dm42,
  },
  'components/image-viewer/index.zh': {
    frontmatter: fm43,
    toc: toc43,
    texts: txt43,
    demos: dm43,
  },
  'components/image/index.en': {
    frontmatter: fm44,
    toc: toc44,
    texts: txt44,
    demos: dm44,
  },
  'components/image/index.zh': {
    frontmatter: fm45,
    toc: toc45,
    texts: txt45,
    demos: dm45,
  },
  'components/index-bar/index.zh': {
    frontmatter: fm46,
    toc: toc46,
    texts: txt46,
    demos: dm46,
  },
  'components/infinite-scroll/index.en': {
    frontmatter: fm47,
    toc: toc47,
    texts: txt47,
    demos: dm47,
  },
  'components/infinite-scroll/index.zh': {
    frontmatter: fm48,
    toc: toc48,
    texts: txt48,
    demos: dm48,
  },
  'components/input/index.en': {
    frontmatter: fm49,
    toc: toc49,
    texts: txt49,
    demos: dm49,
  },
  'components/input/index.zh': {
    frontmatter: fm50,
    toc: toc50,
    texts: txt50,
    demos: dm50,
  },
  'components/jumbo-tabs/index.en': {
    frontmatter: fm51,
    toc: toc51,
    texts: txt51,
    demos: dm51,
  },
  'components/jumbo-tabs/index.zh': {
    frontmatter: fm52,
    toc: toc52,
    texts: txt52,
    demos: dm52,
  },
  'components/list/index.en': {
    frontmatter: fm53,
    toc: toc53,
    texts: txt53,
    demos: dm53,
  },
  'components/list/index.zh': {
    frontmatter: fm54,
    toc: toc54,
    texts: txt54,
    demos: dm54,
  },
  'components/loading/index.en': {
    frontmatter: fm55,
    toc: toc55,
    texts: txt55,
    demos: dm55,
  },
  'components/loading/index.zh': {
    frontmatter: fm56,
    toc: toc56,
    texts: txt56,
    demos: dm56,
  },
  'components/mask/index.en': {
    frontmatter: fm57,
    toc: toc57,
    texts: txt57,
    demos: dm57,
  },
  'components/mask/index.zh': {
    frontmatter: fm58,
    toc: toc58,
    texts: txt58,
    demos: dm58,
  },
  'components/nav-bar/index.en': {
    frontmatter: fm59,
    toc: toc59,
    texts: txt59,
    demos: dm59,
  },
  'components/nav-bar/index.zh': {
    frontmatter: fm60,
    toc: toc60,
    texts: txt60,
    demos: dm60,
  },
  'components/page-indicator/index.en': {
    frontmatter: fm61,
    toc: toc61,
    texts: txt61,
    demos: dm61,
  },
  'components/page-indicator/index.zh': {
    frontmatter: fm62,
    toc: toc62,
    texts: txt62,
    demos: dm62,
  },
  'components/popover/index.en': {
    frontmatter: fm63,
    toc: toc63,
    texts: txt63,
    demos: dm63,
  },
  'components/popover/index.zh': {
    frontmatter: fm64,
    toc: toc64,
    texts: txt64,
    demos: dm64,
  },
  'components/safe-area/index.en': {
    frontmatter: fm65,
    toc: toc65,
    texts: txt65,
    demos: dm65,
  },
  'components/safe-area/index.zh': {
    frontmatter: fm66,
    toc: toc66,
    texts: txt66,
    demos: dm66,
  },
  'components/scroll-mask/index.en': {
    frontmatter: fm67,
    toc: toc67,
    texts: txt67,
    demos: dm67,
  },
  'components/scroll-mask/index.zh': {
    frontmatter: fm68,
    toc: toc68,
    texts: txt68,
    demos: dm68,
  },
  'components/selector/index.en': {
    frontmatter: fm69,
    toc: toc69,
    texts: txt69,
    demos: dm69,
  },
  'components/selector/index.zh': {
    frontmatter: fm70,
    toc: toc70,
    texts: txt70,
    demos: dm70,
  },
  'components/side-bar/index.en': {
    frontmatter: fm71,
    toc: toc71,
    texts: txt71,
    demos: dm71,
  },
  'components/side-bar/index.zh': {
    frontmatter: fm72,
    toc: toc72,
    texts: txt72,
    demos: dm72,
  },
  'components/space/index.en': {
    frontmatter: fm73,
    toc: toc73,
    texts: txt73,
    demos: dm73,
  },
  'components/space/index.zh': {
    frontmatter: fm74,
    toc: toc74,
    texts: txt74,
    demos: dm74,
  },
  'components/stepper/index.en': {
    frontmatter: fm75,
    toc: toc75,
    texts: txt75,
    demos: dm75,
  },
  'components/stepper/index.zh': {
    frontmatter: fm76,
    toc: toc76,
    texts: txt76,
    demos: dm76,
  },
  'components/steps/index.en': {
    frontmatter: fm77,
    toc: toc77,
    texts: txt77,
    demos: dm77,
  },
  'components/steps/index.zh': {
    frontmatter: fm78,
    toc: toc78,
    texts: txt78,
    demos: dm78,
  },
  'components/swiper/index.en': {
    frontmatter: fm79,
    toc: toc79,
    texts: txt79,
    demos: dm79,
  },
  'components/swiper/index.zh': {
    frontmatter: fm80,
    toc: toc80,
    texts: txt80,
    demos: dm80,
  },
  'components/switch/index.en': {
    frontmatter: fm81,
    toc: toc81,
    texts: txt81,
    demos: dm81,
  },
  'components/switch/index.zh': {
    frontmatter: fm82,
    toc: toc82,
    texts: txt82,
    demos: dm82,
  },
  'components/tab-bar/index.en': {
    frontmatter: fm83,
    toc: toc83,
    texts: txt83,
    demos: dm83,
  },
  'components/tab-bar/index.zh': {
    frontmatter: fm84,
    toc: toc84,
    texts: txt84,
    demos: dm84,
  },
  'components/tabs/index.en': {
    frontmatter: fm85,
    toc: toc85,
    texts: txt85,
    demos: dm85,
  },
  'components/tabs/index.zh': {
    frontmatter: fm86,
    toc: toc86,
    texts: txt86,
    demos: dm86,
  },
  'components/tag/index.en': {
    frontmatter: fm87,
    toc: toc87,
    texts: txt87,
    demos: dm87,
  },
  'components/tag/index.zh': {
    frontmatter: fm88,
    toc: toc88,
    texts: txt88,
    demos: dm88,
  },
  'components/text-area/index.en': {
    frontmatter: fm89,
    toc: toc89,
    texts: txt89,
    demos: dm89,
  },
  'components/text-area/index.zh': {
    frontmatter: fm90,
    toc: toc90,
    texts: txt90,
    demos: dm90,
  },
  'components/toast/index.en': {
    frontmatter: fm91,
    toc: toc91,
    texts: txt91,
    demos: dm91,
  },
  'components/toast/index.zh': {
    frontmatter: fm92,
    toc: toc92,
    texts: txt92,
    demos: dm92,
  },
  'components/water-mark/index.en': {
    frontmatter: fm93,
    toc: toc93,
    texts: txt93,
    demos: dm93,
  },
  'components/water-mark/index.zh': {
    frontmatter: fm94,
    toc: toc94,
    texts: txt94,
    demos: dm94,
  },
}

// generate demos data in runtime, for reuse route.id to reduce bundle size
export const demos = Object.entries(filesMeta).reduce((acc, [id, meta]) => {
  // append route id to demo
  Object.values(meta.demos).forEach((demo) => {
    demo.routeId = id;
  });
  // merge demos
  Object.assign(acc, meta.demos);

  // remove demos from meta, to avoid deep clone demos in umi routes/children compatible logic
  delete meta.demos;

  return acc;
}, {});
